CrimeInvestigationSystem/Controllers/InvestigationController.cs
using CrimeInvestigationSystem.Models;
using CrimeInvestigationSystem.Models.Utility;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrimeInvestigationSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InvestigationController : Controller
    {
        private ApplicationDbContext con;
        public InvestigationController()
        {
            con = new ApplicationDbContext();
        }


        #region      CRIME CRUD

        [HttpGet]
        public ActionResult Crime(string profileId = null)
        {
            string msg = "";

            if (TempData["Msg"] != null)
            {
                ViewBag.Msg = TempData["Msg"].ToString();
            }


            try
            {

                if (TempData["profileID"] != null && TempData["profileID"].ToString() != "")
                {
                    profileId = TempData["profileID"].ToString();
                }


                var crimes = con.Crimes.Where(x => x.ProfileID == profileId).ToList();
                if (crimes.Count > 0)
                {
                    msg = "Add new Record";
                    ViewBag.Crimes = crimes;
                    ViewBag.CrimeCount = crimes.Count;
                    TempData["profileID"] = profileId;
                }
                else
                {
                    TempData["profileID"] = profileId;
                    msg = "Add new Record";
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null)
                    msg = "TRY AGAIN LATER, IF PERSISTED, CONTACT ADMIN! \n" + ex.InnerException.Message.ToString();
                else
                    msg = "TRY AGAIN LATER, IF PERSISTED, CONTACT ADMIN! \n" + ex.Message.ToString();
            }

            ViewBag.Msg = msg;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crime(Crime model)
        {
            string msg = "";
            if (model.Id == null)
            {
                var util = new Utilities();
                var genId = util.RandomDigits(11);
                model.Id = genId;
            }

            //jsonReturningMessage jsonRMsg = null;

            try
            {


                //  PROCESS IMAGE
                // CHECK IF IMAGE1 UPLOAD FILE IS EMPTY
                if (model.PhotoUpload == null || model.PhotoUpload.ContentLength < 0)
                {
                    msg = "Please select crime photo, and Try again!";
                    TempData["profileID"] = model.ProfileID;
                    //jsonRMsg = new jsonReturningMessage()
                    //{
                    //    Profileid = model.ProfileID,
                    //    Message = msg
                    //};
                    //return Json(jsonRMsg, JsonRequestBehavior.AllowGet);
                    TempData["Msg"] = msg;
                    return RedirectToAction("Crime", new { profileId = model.ProfileID });
                }
                else if (model.PhotoUpload != null &&
                         model.PhotoUpload.ContentLength > 0 &&
                         model.PhotoUpload.FileName.ToLower().EndsWith("jpeg") ||
                         model.PhotoUpload.FileName.ToLower().EndsWith("jpg") ||
                         model.PhotoUpload.FileName.ToLower().EndsWith("png"))
                {
                    //UPLOAD NOT EMPTY

                    string crimeTitle = DateTime.Now.ToString("dd/MM/yyyy:HH:mm:ss").Replace("/", "_").Replace(":", "_") + Path.GetExtension(model.PhotoUpload.FileName);

                    string pathx = Server.MapPath("~/Uploads/Passports/" + crimeTitle);
                    model.PhotoUpload.SaveAs(pathx);

                    if (pathx != null)
                    {
                        using (Image img = Image.FromFile(pathx))
                        {
                            var ms = new MemoryStream();

                            img.Save(ms, ImageFormat.Jpeg);

                            var bytes = ms.ToArray();

                            // NOW SAVE BYTE WITH STUDENT REGNO NUMBER
                            if (bytes.Length > 0)
                            {

                                model.Photo = bytes;

                            }
                            else
                            {
                                msg = "Image conversion failed!";
                                TempData["Msg"] = msg;
                                return RedirectToAction("Crime", new { profileId = model.ProfileID });
                                //return Json(msg, JsonRequestBehavior.AllowGet);
                            }
                        }
                    }
                }
                else
                {
                    msg = "Please select crime photo in jpg, jpeg, png format, and Try again!";
                    //jsonRMsg = new jsonReturningMessage()
                    //{
                    //    Profileid = model.ProfileID,
                    //    Message = msg
                    //};
                    //return Json(jsonRMsg, JsonRequestBehavior.AllowGet);
                    TempData["Msg"] = msg;
                    return RedirectToAction("Crime", new { profileId = model.ProfileID });

                }
                if (model.ProfileID == null)
                {
                    model.ProfileID = TempData["profileID"].ToString();
                }

                TempData["profileID"] = model.ProfileID;


                var dbObj = con.Crimes.SingleOrDefault(o => o.Id == model.Id);
                if (dbObj != null)
                {
                    // JUST UPDATE - CRIME Table

                    dbObj.DefaultedLaw = model.DefaultedLaw;
                    dbObj.CommittedDate = model.CommittedDate;
                    dbObj.AddressofCrime = model.AddressofCrime;
                    dbObj.Tried = model.Tried;
                    dbObj.Type = model.Type;
                    dbObj.Photo = model.Photo;



                    con.SaveChanges();
                    msg = "Crime record has been updated successfully!";
                }
                else
                {
                    // CREATE NEW RECORD

                    model = new Crime()
                    {
                        DefaultedLaw = model.DefaultedLaw,
                        CommittedDate = model.CommittedDate,
                        AddressofCrime = model.AddressofCrime,
                        Tried = model.Tried,
                        Type = model.Type,
                        Photo = model.Photo,
                        CreatedAt = DateTime.UtcNow,
                        ProfileID = TempData["profileID"].ToString()
                    };

                    con.Crimes.Add(model);
                    TempData["profileID"] = model.ProfileID;

                    con.SaveChanges();
                    msg = "Crime record has been created successfully!";

                }

            }
            catch (Exception ex)
            {
                if (ex.InnerException != null)
                    msg = "TRY AGAIN, IF PERSISTED, CONTACT ADMIN! \n" + ex.InnerException.Message.ToString();
                else
                    msg = "TRY AGAIN, IF PERSISTED, CONTACT ADMIN! \n" + ex.Message.ToString();
            }

            //jsonRMsg = new jsonReturningMessage()
            //{
            //    Profileid = model.ProfileID,
            //    Message = msg
            //};
            //return Json(jsonRMsg, JsonRequestBehavior.AllowGet);
            TempData["Msg"] = msg;
            return RedirectToAction("Crime", new { profileId = model.ProfileID });

        }

        [AllowAnonymous]
        public ActionResult AddEditCrime(string crimeId)
        {
            string msg = "";
            string profileID = "";

            if (TempData["profileID"] != null)
            {
                profileID = TempData["profileID"].ToString();
            }

            try
            {
                ViewBag.profileID = profileID;

                //if (TempData["crimeProfileID"] != null)
                //{
                //    profileID = TempData["crimeProfileID"].ToString();
                //}

                UtilityHelpers utilityHelpers = new UtilityHelpers();

                ViewBag.CrimeTypeList = utilityHelpers.CrimeTypeList();

                if (crimeId != null)
                {
                    var obj = con.Crimes.SingleOrDefault(o => o.Id == crimeId);
                    if (obj != null)
                    {

                        Crime objCrime = new Crime()
                        {
                            DefaultedLaw = obj.DefaultedLaw,
                            CommittedDate = obj.CommittedDate,
                            AddressofCrime = obj.AddressofCrime,
                            Tried = obj.Tried,
                            Id = obj.Id,
                            Type = obj.Type,
                            CreatedAt = DateTime.UtcNow,
                            ProfileID = obj.ProfileID
                        };
                        return PartialView("AddEditCrime", objCrime);
                    }
                }
                var model = new Crime()
                {
                    ProfileID = profileID
                };

                return PartialView("AddEditCrime", model);

            }
            catch (Exception ex)
            {
                if (ex.InnerException != null)
                    msg = "TRY AGAIN LATER, IF PERSISTED, CONTACT ADMIN! \n" + ex.InnerException.Message.ToString();
                else
                    msg = "TRY AGAIN LATER, IF PERSISTED, CONTACT ADMIN! \n" + ex.Message.ToString();

CrimeInvestigationSystem/Controllers/RoleController.cs
using CrimeInvestigationSystem.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CrimeInvestigationSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {

        ApplicationDbContext context;
        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Roles
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            var roles = context.Roles.ToList();
            return View(roles);
        }


        /// Create  a New role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary>
        /// Create a New Role
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            if (Role.Name == null)
            {
                ViewBag.Msg = "Invalid data provided, please try again with valid data!";
                return View();
            }
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Users
        public ActionResult UserRoles()
        {


            if (User.Identity.IsAuthenticated)
            {

                var userRolesModel = new List<UserRoleModel>();

                var lstUsers = context.Users.ToList();

                foreach (var user in lstUsers)
                {
                    foreach (var role in user.Roles)
                    {
                        var rol = context.Roles.Where(x => x.Id == role.RoleId).FirstOrDefault();
                        if (rol != null)
                        {
                            userRolesModel.Add(new UserRoleModel
                            {
                                User = user.UserName,
                                Role = rol.Name,
                                UserId = user.Id
                            });
                        }

                    }
                }
                return View(userRolesModel);


            }
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public ActionResult RoleAssignment()
        {
            var lstRole = context.Roles.ToList();
            ViewBag.RoleId = new SelectList(lstRole, "Name", "Name");

            var lstUsers = context.Users.ToList();
            ViewBag.UserId = new SelectList(lstUsers, "Id", "Email");



            return View();
        }


        [HttpPost]
        public ActionResult RoleAssignment(string userId, string role)
        {
            
            if (userId == "" || role == "")
            {
                var lstRole = context.Roles.ToList();
                ViewBag.RoleId = new SelectList(lstRole, "Name", "Name");

                var lstUsers = context.Users.ToList();
                ViewBag.UserId = new SelectList(lstUsers, "Id", "Email");

                ViewBag.Msg = "Please select user email address and role before you submit!";
                return View();
            }
            else
            {
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));



                var resiltX = UserManager.AddToRole(userId, role);
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Delete(string ID)
        {

            string msg = "";


            if (ID != null)
            {
                var objDel = context.Users.SingleOrDefault(o => o.Id == ID);
                if (objDel != null)
                {
                    context.Users.Remove(objDel);
                    context.SaveChanges();

                    msg = "1";
                }
                else
                {
                    msg = "0";
                }
            }
            return RedirectToAction("UserRoles");
        }

        public static IdentityResult AddToRole(string userId, string role)
        {

            return null;
        }
                

        public bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                // ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

CrimeInvestigationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - NPF Investigation System</title>
    <link rel="icon" href="~/Images/policeLogo.png" type="image/gif" />

    @* BOOTSTRAP 5 CDN *@
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/css/bootstrap.css.map">



    @*<link href="~/Content/bootstrapx.css" rel="stylesheet" />
        <link href="~/Content/bootstrapx.css.map" rel="stylesheet" />*@
    <link href="~/Content/font-awesome.css" rel="stylesheet" />

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/main.css">
    <!--===============================================================================================-->

    <link href="~/Content/style.css" rel="stylesheet" />

    <link href="~/Content/Custom.css" rel="stylesheet" />

    <style>
        a {
            text-decoration: none;
            color: red;
        }
    </style>

</head>
<body>


    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index","Home")">  <b class="lead">&nbsp; <i class="fa fa-arrow-circle-left"></i> &nbsp; NPF Biometric System</b></a></li>
            </ul>
            <div class="d-flex d-none d-sm-block text-light pe-4">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-power-off pe-2 text-danger"></i> Log off</a>
                }
                else
                {
                    <a class="nav-link" href="@Url.Action("Login","Account")"><i class="fa fa-user-circle-o pe-2 text-primary"></i> Log In</a>
                }
            </div>
            <div class="offcanvas offcanvas-end text-bg-dark" style="border-left:4px solid whitesmoke;" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">

                <div class="offcanvas-header">

                    <h6 class="offcanvas-title ps-2" id="offcanvasDarkNavbarLabel">MENU</h6>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">


                    @if (User.IsInRole("Student") && Session["stdPass"] != null)
                    {
                        string imgPath = Session["stdPass"].ToString();
                        <img src="http://www.esiwes.com.ng/Uploads/Passports/@imgPath" style="border-radius: 50%; width: 100px; height:100px; margin-left:130px" class="img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/Images/anonymous-User.png" width="60" height="60" style="border-radius: 50%; width: 100px; height: 100px; margin-left: 130px" class="img-thumbnail" />
                    }
                    <div class="row">
                        <h6 class="text-center pt-2">Hi - @User.Identity.Name</h6>
                    </div>

                    <hr />
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">

                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index","Home")"><i class="fa fa-home fa-3x text-warning"></i></a>

                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle p-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Manager
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">

                                    <li class="dropdown-header fw-bolder p-2 mt-2 fw-bold ">Role Management</li>

                                    <li>
                                        <hr class="dropdown-header fw-bolder text-primary fw-bolder text-primary">
                                    </li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index","Role")">Available Roles</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Create","Role")">New Role</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("UserRoles","Role")">User in Role</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("RoleAssignment","Role")">Role Assignment</a></li>

                                    <li class="dropdown-header fw-bolder p-2 mt-2 fw-bold ">App Manager</li>

                                    <li>
                                        <hr class="dropdown-header fw-bolder text-primary fw-bolder text-primary">
                                    </li>
                                    <li><a class="dropdown-item" href="@Url.Action("UsersProfile","Admin")">User Profile</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("UploadPassport","Admin")">Upload Passport</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("UploadFingerPrint","Admin")">Upload Finger Print</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("ComparePrints","Investigation")">Compare Suspect Print</a></li>
                                    <li>
                                        <hr class="dropdown-header fw-bolder text-primary fw-bolder text-primary">
                                    </li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>

                        }
                        @if (User.IsInRole(""))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle p-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Dashboard
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li class="dropdown-header fw-bolder p-2 mt-2 fw-bold ">Customers Account</li>

                                    <li>
                                        <hr class="dropdown-header fw-bolder text-primary fw-bolder text-primary">
                                    </li>
                                     <li><a class="dropdown-item" href="@Url.Action("Transactions","Transaction")">Transactions Ledger</a></li>
                                </ul>
                            </li>

                        }

                    </ul>

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </nav>

    <div class="container" id="body">
        <br />
        <br />
        <br />
        @RenderBody()

        <footer class="">
            <div class="row">



                    <section class="get_in_touch">

                        <h1 id="title">
                            Contact us now
                        </h1>

                        <div class="row contact-form">

                            <form class="row ">

                                <div class="form-field col-lg-12 mt-2">
                                    <input type="email" class="form-control" id="Email" name="Email" placeholder="Email address" required>
                                </div>

                                <div class="form-field col-lg-12 mt-2">
                                    <input type="text" class="form-control" id="Subject" name="Subject" placeholder="Subject" required>
                                </div>

                                <div class="form-field col-lg-12 mt-2">
                                    <textarea id="Message" class="form-control" placeholder="Complain in details" name="Message" required></textarea>
                                </div>

                                <div class="d-grid gap-2 col-md-12 mx-auto mt-2">
                                    <button class="btn btnSendMsg btn-danger" type="submit">Send</button>
                                </div>

                                <div style="text-align: center;" id="loaderDiv1x">
                                    <img src="~/Images/loadingx.gif" width="80" height="80" class="img img-thumbnail" />
                                </div>
                            </form>
                        </div>
                    </section>

            </div>
            <p class="cpy">&copy; @DateTime.Now.Year - NPF BIOMETRIC SYSTEM</p>

        </footer>
    </div>

    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/js/bootstrap.bundle.min.js" integrity="sha512-BOsvKbLb0dB1IVplOL9ptU1EYA+LuCKEluZWRUYG73hxqNBU85JBIBhPGwhQl7O633KtkjMv8lvxZcWP+N3V3w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/tilt/tilt.jquery.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/mainxyz.js"></script>
</body>
</html>

<script>

    $(document).ready(function () {
        $("#loaderDiv1x").hide();

        $(".btnSendMsg").click(function () {

            $("#loaderDiv1x").show();

            var email = $("#Email").val();
            var subject = $("#Subject").val();
            var message = $("#Message").val();
            debugger
            if (email === "" || subject === "" || message === "") {
                alert("Please, kindly check the filed you're leaving blank, fill all field!");
                $("#loaderDiv1x").hide();
            } else {
                $.ajax({
                    type: "POST",
                    url: "/Utility/CreateTicket",
                    data: { Email: email, Subject: subject, Message: message },
                    success: function (result) {
                        $("#loaderDiv1x").hide();
                        if (result.trim != "" || result.trim != null) { alert(result); }
                        window.location.href = "/Home/Index";
                    }
                })
            }
        })

    })
</script>